// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMdhXJCsriHUaE3Jc7ZI3vQhIpYKUe4f0',
    appId: '1:844599229027:web:1710b13bfcbb8a4c0dd656',
    messagingSenderId: '844599229027',
    projectId: 'sendora-9e14f',
    authDomain: 'sendora-9e14f.firebaseapp.com',
    storageBucket: 'sendora-9e14f.appspot.com',
    measurementId: 'G-80MRPB5XRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMlzPZ811HLbFrV-6toffm1rR9iVoRmp0',
    appId: '1:844599229027:android:b35e25cf8c6853df0dd656',
    messagingSenderId: '844599229027',
    projectId: 'sendora-9e14f',
    storageBucket: 'sendora-9e14f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmnguhladjB7mcNXVojDilJH_rFhfaK30',
    appId: '1:844599229027:ios:aa29db31b3b024530dd656',
    messagingSenderId: '844599229027',
    projectId: 'sendora-9e14f',
    storageBucket: 'sendora-9e14f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmnguhladjB7mcNXVojDilJH_rFhfaK30',
    appId: '1:844599229027:ios:aa29db31b3b024530dd656',
    messagingSenderId: '844599229027',
    projectId: 'sendora-9e14f',
    storageBucket: 'sendora-9e14f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMdhXJCsriHUaE3Jc7ZI3vQhIpYKUe4f0',
    appId: '1:844599229027:web:92f259cfb19a77240dd656',
    messagingSenderId: '844599229027',
    projectId: 'sendora-9e14f',
    authDomain: 'sendora-9e14f.firebaseapp.com',
    storageBucket: 'sendora-9e14f.appspot.com',
    measurementId: 'G-5VSS5MG3G3',
  );
}
